name: DupeVault
version: '${version}'
main: strictpvp.dupeVault.DupeVault
api-version: '1.13'
authors: [ strict_pvp ]
folia-supported: true

commands:
  reloadconfig:
    description: reload dupe config
    permission: op
    usage: /reloadconfig
